# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  displayName: 'Install packages'
  inputs:
    command: 'install'
    
- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/stoneassemblies/stoneassemblies.github.io.git public'
    
- task: Npm@1
  displayName: 'Build'
  inputs:
    command: 'custom'
    customCommand: 'run build'

