# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: 'Set Node.js version to 16.x'
  inputs:
    versionSpec: '16.x'

- task: Npm@1
  displayName: 'Install packages'
  inputs:
    command: 'install'
    
- task: Npm@1
  displayName: 'Build'
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: CmdLine@2
  displayName: 'Update GitHub page'
  inputs:
    script: |
      git config --global user.email "alexander.fernandez.sauco@gmail.com"
      git config --global user.name "Igr Alexánder Fernández Saúco"
      git clone https://$GITHUB_TOKEN@github.com/stoneassemblies/stoneassemblies.github.io.git sync
      cp -R public/* sync/
      cd sync
      git add -A 
      git commit -a -m "Update web site "
      git push origin
      cd ..
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)